### ISSUE TITLE
Communication platform

### ISSUE THREAD

**Issue by edvinnn** [Hampusholmstrom/M7012E-phewstoc#10]
Which communication should we use for this project besides IRL talks and issues on GitHub?

**Comment by willeponken** [comment]
Hmmm

**Comment by willeponken** [comment]
Conversations group?

**Comment by willeponken** [comment]
Mail group?

**Comment by willeponken** [comment]
Both you, me, Philip and Hampus already has XMPP/Cokversations

**Comment by willeponken** [comment]
Swish?

**Comment by edvinnn** [comment]
> Both you, me, Philip and Hampus already has XMPP/Conversations

That's true, but I don't like Conversations since my battery don't like to decipher your messages...

**Comment by willeponken** [comment]
We could all use OMEMO instead of GPG

**Comment by willeponken** [comment]
Slack never show any notifications for me

**Comment by Hjortsberg** [comment]
xmpp or messenger is my 2 cents!

**Comment by willeponken** [comment]
Any progress?

**Comment by willeponken** [comment]
Should we go with Swish?

**Comment by edvinnn** [comment]
> Slack never show any notifications for me

https://get.slack.help/hc/en-us/articles/201355156-Desktop-notifications

**Comment by willeponken** [comment]
We're gonna use Messenger.
