### ISSUE TITLE
Set up endpoint and verify fitbit subscriber

### ISSUE THREAD

**Issue by Hjortsberg** [Hampusholmstrom/M7012E-phewstoc#16]
In order to test the server we need the endpoint.

**Comment by Hjortsberg** [comment]
Let me clarify, I have already implemented the endpoint in the server but we need the URL specified in fitbit service 😃

**Comment by edvinnn** [comment]
> Let me clarify, I have already implemented the endpoint in the server but we need the URL specified in fitbit service 😃

I guessed that's what you meant 💯
