### ISSUE TITLE
Can we merge the two projects we have now?

### ISSUE THREAD

**Issue by edvinnn** [Hampusholmstrom/M7012E-phewstoc#18]
Since we won't work with facial expressions at this time, I think it would be better if we merged the projects here on GitHub. It would also give us a better understanding on how the issues are progressing if we have al the issues in one project.

**Comment by edvinnn** [comment]
Any input on this? @willeponken @Hampusholmstrom @Hjortsberg

**Comment by willeponken** [comment]
Which two projects? I don't really understand what you mean.

**Comment by edvinnn** [comment]
> Which two projects? I don't really understand what you mean.

Projects here on GitHub. We have two now. You can see them at the top bar... 

| Code | Issues | Pull requests || Projects || Wiki | Insights |

**Comment by willeponken** [comment]
Ah, yes either merge them or rename yours to Sleep detection?

**Comment by edvinnn** [comment]
> Ah, yes either merge them or rename yours to Sleep detection?

Nice. I'll merge them since we don't have many issues open right now. If we get a overload of open issues we can split again 👍
