### ISSUE TITLE
Intervention about @Hjortsberg's avatar

### ISSUE THREAD

**Issue by willeponken** [Hampusholmstrom/M7012E-phewstoc#4]
@Hjortsberg doesn't drink coffee on his avatar like me and @Hampusholmstrom does.

**Comment by edvinnn** [comment]
I'll fix that ASAP. My no. 1 prio atm

**Comment by willeponken** [comment]
Great! Looking forward to a great avatar!

**Comment by willeponken** [comment]
Any progress on this?
