### ISSUE TITLE
Pre-study: Literature

### ISSUE THREAD

**Issue by willeponken** [Hampusholmstrom/M7012E-phewstoc#5]
Find some good material and link here.

**Comment by willeponken** [comment]
Frameworks and libraries:
http://openbiometrics.org/docs/index.html
https://cmusatyalab.github.io/openface/
https://opencv.org/
https://deepface.ir/

**Comment by Hjortsberg** [comment]
https://www.yorku.ca/mack/hcii2018b.pdf
https://www.researchgate.net/profile/Vitalii_Pertsevyi/post/Designing_an_eye_tracking_experiment/attachment/59d636ce79197b8077994359/AS:390485614055431@1470110434081/download/Andrew+Duchowski+BSc%2CPhD+%28auth.%29-Eye+Tracking+Methodology_+Theory+and+Practice-Springer-Verlag+London+%282007%29.pdf
https://patentimages.storage.googleapis.com/ed/d4/e9/abd7dd4cfae056/US5991429.pdf
https://www.researchgate.net/profile/Yoshihisa_Ijiri/publication/4241655_Security_Management_for_Mobile_Devices_by_Face_Recognition/links/0046353718ccbe083e000000/Security-Management-for-Mobile-Devices-by-Face-Recognition.pdf?origin=publication_detail
https://res.mdpi.com/computers/computers-07-00037/article_deploy/computers-07-00037.pdf?filename=&attachment=1

**Comment by Hjortsberg** [comment]
Oh sorry, my links above reference the literal literature study, I.E the scientific research papers.

**Comment by edvinnn** [comment]
I found [this](https://research.fb.com/wp-content/uploads/2016/11/deepface-closing-the-gap-to-human-level-performance-in-face-verification.pdf?) research paper on facebooks deepface

**Comment by edvinnn** [comment]
And here is another one http://www.robots.ox.ac.uk/~vgg/publications/2015/Parkhi15/parkhi15.pdf

**Comment by Hjortsberg** [comment]
Paper on FER with HOG 
https://www.ncbi.nlm.nih.gov/pmc/articles/PMC4628009/

**Comment by willeponken** [comment]
@Hjortsberg Wanna link the Fitbit paper?

**Comment by Hjortsberg** [comment]
https://www.ncbi.nlm.nih.gov/pmc/articles/PMC4683756/

**Comment by willeponken** [comment]
Heh...

1. http://www.robots.ox.ac.uk/~vgg/publications/2015/Parkhi15/parkhi15.pdf
2. https://research.fb.com/wp-content/uploads/2016/11/deepface-closing-the-gap-to-human-level-performance-in-face-verification.pdf?
3. https://www.ncbi.nlm.nih.gov/pmc/articles/PMC4683756/
4. https://www.researchgate.net/profile/Vitalii_Pertsevyi/post/Designing_an_eye_tracking_experiment/attachment/59d636ce79197b8077994359/AS:390485614055431@1470110434081/download/Andrew+Duchowski+BSc%2CPhD+%28auth.%29-Eye+Tracking+Methodology_+Theory+and+Practice-Springer-Verlag+London+%282007%29.pdf

**Comment by Hjortsberg** [comment]
WHAT, WHO DIS
https://www.researchgate.net/publication/221410595_Energy_saving_of_TV_by_face_detection

**Comment by willeponken** [comment]
The Specter of Malicious Computing: Securing the Internet of Things https://ieeexplore.ieee.org/abstract/document/8490178

State-of-the-art survey on P2P overlay networks in pervasive computing environments https://www.sciencedirect.com/science/article/pii/S1084804515000879

Runtime Detection of the Concurrency Property in Asynchronous Pervasive Computing Environments https://link.springer.com/chapter/10.1007/978-981-10-2546-4_10


Fault-avoidance strategies for context-aware schedulers in pervasive computing systems https://ieeexplore.ieee.org/abstract/document/7917853

Human activity recognition with smartphone sensors using deep learning neural networks https://www.sciencedirect.com/science/article/pii/S0957417416302056

Emotions in context: examining pervasive affective sensing systems, applications, and analyses https://link.springer.com/article/10.1007/s00779-015-0842-3

Sensorless sensing with WiFi https://ieeexplore.ieee.org/abstract/document/7040509

Goal-Driven Service Composition in Mobile and Pervasive Computing https://ieeexplore.ieee.org/abstract/document/7416009

Pervasive computing technologies to continuously assess Alzheimer’s disease progression and intervention efficacy https://www.frontiersin.org/articles/10.3389/fnagi.2015.00102/full

Semantic web technologies in pervasive computing: A survey and research roadmap https://www.sciencedirect.com/science/article/pii/S1574119214001989

**Comment by willeponken** [comment]
Dis done.
