### ISSUE TITLE
Pre-study: KODI addons and interaction

### ISSUE THREAD

**Issue by willeponken** [Hampusholmstrom/M7012E-phewstoc#6]
How can KODI be coupled w/ our system?

**Comment by willeponken** [comment]
And OS specifics.

**Comment by willeponken** [comment]
JSON-RPC API for KODI: https://kodi.wiki/view/JSON-RPC_API/v9#Input

**Comment by willeponken** [comment]
Face recognition would probably just send a shutdown and start signal with CEC: https://github.com/Pulse-Eight/libcec

**Comment by Hjortsberg** [comment]
Any progress on this?!

**Comment by edvinnn** [comment]
Consider this done for now?

**Comment by willeponken** [comment]
This is done! @Hampusholmstrom has succesfully switched profiles remotely. :cake:
