### ISSUE TITLE
Pre-study: Face recognition

### ISSUE THREAD

**Issue by willeponken** [Hampusholmstrom/M7012E-phewstoc#9]
How?! Both detection and authentication. @edvinnn

**Comment by edvinnn** [comment]
Based on my research I would say OpenCV is the most competent and extensive library available, but it might be overkill for us. From what I can conclude at this moment I think we should further investigate this librarie for now:

-  [OpenFace](http://cmusatyalab.github.io/openface/) - [Source](https://github.com/cmusatyalab/openface)

Worth watching
- [Facenet](https://github.com/davidsandberg/facenet)

**Comment by willeponken** [comment]
I thought OpenCV was more low level?

**Comment by willeponken** [comment]
Oh, you kind of said that, sorry

**Comment by willeponken** [comment]
Have you looked at DeepFace?

**Comment by edvinnn** [comment]
> Have you looked at DeepFace?

Yeah, I have. If you mean this https://deepface.ir/ it seems to be a paid service. 

> I thought OpenCV was more low level?

Exactly, therefore giving huge opportunities... but if we find something narrow that suits us it just might be more pleasant to work with. What do you think?

**Comment by willeponken** [comment]
What language do you guys want to use?

**Comment by willeponken** [comment]
`face_recognition` has problems w/ the distance, I'll check if it's the same w/ OpenFace.

**Comment by edvinnn** [comment]
How is this progressing? I think we are past the pre-study phase here? @willeponken
